/**
 * Stock Symbol Mappings
 * 
 * This file contains mappings between symbol names in My_Track.csv 
 * and their corresponding names in today_price.csv
 * 
 * Format: 
 *   'SYMBOL_IN_MY_TRACK': 'SYMBOL_IN_TODAY_PRICE'
 * 
 * Example:
 *   'ABCAPITAL': 'ADITYA BIRLA CAPITAL LTD.'
 */

/**
 * List of symbols to ignore during price updates
 * These symbols will be skipped and won't trigger "Not found" warnings
 */
export const IGNORED_SYMBOLS: string[] = [
    'ABSLBANETF',
    'AONETMMQ50',
    'INDO-RE2',
    'LOWVOL1',
    'LICNETFN50',
    'AUTOIETF',
    'BANKBEES',
    'BANKETF',
    'FINIETF',
    'NIFTYETF',
    'ARFIN',
    'GAYAPROJ',
    'PVTBANIETF',
    'QNIFTY',
    'QUALITY30',
    'SENSEXADD',
    'AXSENSEX',
    'BSLNIFTY',
    'ENIFTY',
    'GOLDETF',
    'MOM100',
    'MOM50',
    'PSUBNKBEES',
    'SETFNIFBK',
    'BANKETFADD',
    'SBIETFPB',
    'EBANKNIFTY',
    'HDFCSENSEX',
    'GROWWCAPM',
    'MASPTOP50',
    'MOMNC',
    'SILVER360',
    'ESG',
    'NIF10GETF',
    'NIFTYBEES',
    'SCML',
    'BSLSENETFG',
    'CHOICEGOLD',
    'EQUAL200',
    'HDFCMID150',
    'HDFCGROWTH',
    'AXISNIFTY',
    'BBNPNBETF',
    'GROWWPOWER',
    'IDFNIFTYET',
    'LOWVOLIETF',
    'LTGILTBEES',
    'LTGILTCASE',
    'TOP10ADD',
    'QUAL30IETF',
    'TOP15IETF',
    'SBISILVER',
    'SILVER1',
    'TATSILV',
    'SETFGOLD',
    'TATAGOLD',
    'HDFCNIFBAN',
    'AXISBNKETF',
    'AXISGOLD',
    'EGOLD',
    'ESILVER',
    'GOLD1',
    'GOLDBEES',
    'GOLDBND',
    'GOLDSHARE',
    'GROWWGOLD',
    'HDFCGOLD',
    'METAL',
    'QGOLDHALF',
    'SILVER',
    'SILVERADD',
    'SILVERAG',
    'SILVERBEES',
    'SILVERBND',
    'SILVERCASE',
    'SILVERIETF',
    'AXISILVER',
    'BBNPPGOLD',
    'GOLDCASE',
    'GOLDIETF',
    'MANUFGBEES',
    'SILVERETF',
    'UNIONGOLD',
    'UTIBANKETF',
    'AXISILVER',
    'BBNPPGOLD',
    'GOLDCASE',
    'GOLDIETF',
    'LICMFGOLD',
    'MANUFGBEES',
    'SILVERETF',
    'UTIBANKETF',
    'GROWWSLVR',
    'HDFCSILVER',
    'MOSILVER',
    'MIDCAPADD',
    'SMALLADD',
    'INFRAIETF',
    'MOGOLD',
    'DIVOPPBEES',
    'GOLDADD',
    'GROWWEV',
    'GROWWMETAL',
    'HDFCQUAL',
    'LOWVOL',
    'TNIDETF',
    'TOP100CASE',
    'TOP20',
    'VAL30IETF',
    'DIVOPPBEES',
























    // stock penny
    'SWANDEF',
    'TAKE',
    'Univa',
    'VCL',
    'EASTSILK',
    'RELIABLE',
    'VENUSREM',
    'GFSTEELS',
    'UNIVAFOODS',
    'GREENLEAF',
    'JPOLYINVST',
    'PSRAJ',
    'TRANSTEEL',
    'UEL',
    'SALSTEEL',
    'EFACTOR',
    'INFLUX',
    'CSSL',
    'INVICTA',
    'SPEB',
    'TEAMGTY',
    'SACHEEROME',
    'NEOCHEM',
    'KNAGRI',
    'SHRIKANHA',
    'VIDYAWIRES',
    'MODINATUR',
    'PATELEG-RE',
    'SMCGLOBAL',
    'SHUBHLAXMI',
    'PARIN',
    'ALPSINDUS',
    'AXITA',
    'NIKITA',
    'ASHWINI',
    'DIVIDEND',
    'DIVINEHIRA',
    'EXIMROUTES',
    'RUDRA',
    'KANDARP',
    'NEUEON',
    'NORBTEAEXP',
    'BAGDIGITAL',
    'NEUEON',












    //new stocks
    'KMEW',
    'LEMERITE',
    'SAWALIYA',
    'MEESHO',
    'MWL',
    'RHETAN',
    'ENCOMPAS',
    'FWSTC',
    'MIDWESTLTD',
    'WAKEFIT',
    'ICICIAMC',
    'BAGDIGITAL',
    'KSHINTL',
    'TATACAP',
    'ICICIAMC',








    // major stock still not able find BHAV COPY
    'M&MFIN',
    'MOTHERSON',
    'SOUTHWEST',
    'SKFINDUS',
    'RMDRIP',
    'Viceroy',
    'VHLTD',
    'MAANALU',
    'MAHASTEEL',
    'TCIFINANCE',
    'ARVEE',
    'MAANALU',






    // low score stocks after 6 months check that is good score or not
    'JAYKAY', // low score = 44 ON 6/12/2025
    'DELPHIFX', //low score = 56 ON 7/12/2025
    'DREDGECORP', //low score = 29 ON 12/12/2025
    'RAMCOSYS', //low score = 42 ON 12/12/2025
    'TMCV', //low score = 36 ON 12/12/2025
    'AEQUS', //low score = 36 ON 29/12/2025






    // 🚨 SECTOR GATE STATUS: ❌ FAIL
    'JETFREIGHT', // 13/12/2025
    'NEPTUNE', // 13/12/2025
    'MODINATUR', // 13/12/2025
    'SHEETAL', // 13/12/2025
    'IDEA', // 13/12/2025
    'GRMOVER', // 29/12/2025
    'SALONA',




];


export const STOCK_MAPPINGS: Record<string, string> = {
    // Add your symbol mappings here
    // 'MY_TRACK_SYMBOL': 'TODAY_PRICE_SYMBOL',

    "ABCAPITAL": "ADITYA BIRLA CAPITAL LTD.",
    "ACCENTMIC": "ACCENT MICROCELL LIMITED",
    "ASAHIINDIA": "ASAHI INDIA GLASS LIMITED",
    "AUBANK": "AU SMALL FINANCE BANK LTD",
    "AXISBNKETF": "AXISAMC - AXISBNKETF",
    "BANKBARODA": "BANK OF BARODA",
    "CANBK": "CANARA BANK",
    "CHOICEGOLD": "CHOICEAMC - CHOICEGOLD",
    "CONNPLEX": "CONNPLEX CINEMAS LIMITED",
    "CUB": "CITY UNION BANK LTD",
    "CUMMINSIND": "CUMMINS INDIA LTD",
    "CUPID": "CUPID LIMITED",
    "GOKULAGRO": "GOKUL AGRO RESOURCES LTD",
    "GROWWNXT50": "GROWWAMC - GROWWNXT50",
    "HDFCGROWTH": "HDFCAMC - HDFCGROWTH",
    "HDFCPSUBK": "HDFCAMC HDFCPSUBK",
    "HDFCNIFBAN": "HDFCAMC - HDFCNIFBAN",
    "HDFCNIFTY": "HDFCAMC - HDFCNIFTY",
    "HEROMOTOCO": "HERO MOTOCORP LIMITED",
    "IIFL": "IIFL FINANCE LIMITED",
    "JAYESH": "JAYESH LOGISTICS LIMITED",
    "LAURUSLABS": "LAURUS LABS LIMITED",
    "LENSKART": "LENSKART SOLUTIONS LTD",
    "LUMAXIND": "LUMAX INDUSTRIES LTD",
    "M&M": "MAHINDRA & MAHINDRA LTD",
    "MAANALU": "MAAN ALUMINIUM LIMITED",
    "MEGAFLEX": "MEGA FLEX PLASTICS LTD",
    "MOSERVICE": "MOTILALAMC - MOSERVICE",
    "MOVALUE": "MOTILALAMC - MOVALUE",
    "MSCIADD": "DSPAMC - MSCIADD",
    "MUTHOOTFIN": "MUTHOOT FINANCE LIMITED",
    "NETF": "TATAAML - NETF",
    "NPBET": "TATAAML - NPBET",
    "PAUSHAKLTD": "PAUSHAK LIMITED",
    "PNB": "PUNJAB NATIONAL BANK",
    "SALSTEEL": "STEEL AUTHORITY OF INDIA",
    "SBC": "SBC EXPORTS LIMITED",
    "SBIETFPB": "SBIAMC - SBIBPB",
    "SHREEJISPG": "SHREEJI SHIPPING GLOBAL L",
    "TMB": "TAMILNAD MERCA BANK LTD",
    "UJJIVANSFB": "UJJIVAN SMALL FINANC BANK",
    "VARROC": "VARROC ENGINEERING LTD.",
    "VEDL": "VEDANTA LIMITED",
    "ACCPL": "ACCRETION PHARMA LIMITED",
    "ADANIPORTS": "ADANI PORT & SEZ LTD",
    "AIAENG": "AIA ENGINEERING LIMITED",
    "BSLSENETFG": "BIRLASLAMC - BSLSENETFG",
    "DELPHIFX": "DELPHI WORLD MONEY LTD",
    "FEDERALBNK": "FEDERAL BANK LTD",
    "GLOBAL": "GLOBAL EDUCATION LIMITED",
    "GMRAIRPORT": "GMR AIRPORTS LIMITED",
    "LUMAXTECH": "LUMAX AUTO TECH LTD",
    "Mangalam Worldwide": "MANGALAM WORLDWIDE LTD",
    "PAYTM": "ONE 97 COMMUNICATIONS LTD",
    "MWL": "MANGALAM WORLDWIDE LTD",
    "POWERINDIA": "HITACHI ENERGY INDIA LTD",
    'RICOAUTO': "RICO AUTO INDUSTRIES LTD",
    "RNPL": "RENOL POLYCHEM LIMITED",
    "SUNLITE": "SUNLITE RECYCLING IND LTD",
    "TMCV": "TATA MOTORS LIMITED",
    "ZFCVINDIA": "ZF COM VE CTR SYS IND LTD",
    "ASHOKLEY": "ASHOK LEYLAND LTD",
    "ASIANPAINT": "ASIAN PAINTS LIMITED",
    "DCBBANK": "DCB BANK LIMITED",
    "JAMNAAUTO": "JAMNA AUTO IND LTD",
    "NEPTUNE": "NEPTUNE PETROCHEMICALS L",
    "PARIN": "PARIN ENTERPRISES LIMITED",
    "RPEL": "RAGHAV PRODUCTIVITY ENH L",
    "UNIONBANK": "UNION BANK OF INDIA",
    "WELINV": "WELSPUN INV & COMM LTD",
    "ANURAS": "ANUPAM RASAYAN INDIA LTD",
    "CANFINHOME": "CAN FIN HOMES LTD",
    "ECLERX": "ECLERX SERVICES LTD",
    "EMMVEE": "EMMVEE PHOTOVOLTAIC PWR L",
    "JAYKAY": "JAYKAY ENTERPRISES LTD",
    "GREENLEAF": "GREENLEAF ENVIROTECH LTD",
    "JETFREIGHT": "JET FREIGHT LOGISTICS LTD",
    "UNIVCABLES": "UNIVERSAL CABLES LTD",
    "HINDCOPPER": "HINDUSTAN COPPER LTD",
    "IMFA": "INDIAN METALS & FERRO",
    "JKTYRE": "JK TYRE & INDUSTRIES LTD",
    "MIDWESTLTD": "MIDWEST LIMITED",
    "PTCIL": "PTC INDUSTRIES LIMITED",
    "SAWALIYA": "SAWALIYA FOOD PRODUCTS L",
    "STEL": "STEL HOLDINGS LIMITED",
    "NATIONALUM": "NATIONAL ALUMINIUM CO LTD",
    "SHRIPISTON": "SHRIRAM PIST. & RING LTD",
    "SKFINDUS": "SKF INDIA LTD",
    "IEX": "INDIAN ENERGY EXC LTD",
    "SUNPHARMA": "SUN PHARMACEUTICAL IND L",
    "ARVEE": "ARVEE LABORATORIES I LTD",
    "DREDGECORP": "DREDGING CORP OF INDIA",
    "ELDEHSG": "ELDECO HSG & IND LTD.",
    "MCX": "MULTI COMMODITY EXCHANGE",
    "EICHERMOT": "EICHER MOTORS LTD",
    "JINDALPHOT": "JINDAL PHOTO LIMITED",
    "PFOCUS": "PRIME FOCUS LIMITED",
    "ESABINDIA": "ESAB INDIA LTD",
    "IDEA": "VODAFONE IDEA LIMITED",
    "RAMCOSYS": "RAMCO SYSTEMS LTD.",
    "RHETAN": "RHETAN TMT LIMITED",
    "SAKAR": "SAKAR HEALTHCARE LIMITED",
    "HCC-RE1": "HINDUSTAN CONSTRUCTION CO",
    "HINDZINC": "HINDUSTAN ZINC LIMITED",
    "IDFCFIRSTB": "IDFC FIRST BANK LIMITED",
    "NAVINFLUOR": "NAVIN FLUORINE INT. LTD",
    "ASHAPURMIN": "ASHAPURA MINECHEM LTD",
    "INFOBEAN": "INFOBEANS TECHNO. LTD.",
    "IRISDOREME": "IRIS CLOTHINGS LIMITED",
    "PASHUPATI": "PASHUPATI COTSPIN LIMITED",
    "SALONA": "SALONA COTSPIN LTD.",
    "SENORES": "SENORES PHARMACEUTICALS L",
    "GPPL": "GUJARAT PIPAVAV PORT LTD",
    "KIRLOSENG": "KIRLOSKAR OIL ENG LTD",
    "SILVERTUC": "SILVER TOUCH TECHNO LTD",
    "AEQUS": "AEQUS LIMITED",
    "INDIACEM": "THE INDIA CEMENTS LIMITED",
    "NEPHROPLUS": "NEPHROCARE HEALTH SERV L",
    "PARKHOSPS": "PARK MEDI WORLD LIMITED",
    "SHRIRAMFIN": "SHRIRAM FINANCE LIMITED",
    "THANGAMAYL": "THANGAMAYIL JEWELLERY LTD",
    "CANHLIFE": "CANARA HSBC LIFE INS CO L",
    "FIEMIND": "FIEM INDUSTRIES LIMITED",
    "HINDALCO": "HINDALCO  INDUSTRIES  LTD",
    "TITAN": "TITAN COMPANY LIMITED",
    "BELRISE": "BELRISE INDUSTRIES LTD",
    "BHARATFORG": "BHARAT FORGE LTD",
    "GRMOVER": "GRM OVERSEAS LIMITED",
    "HAPPYFORGE": "HAPPY FORGINGS LIMITED",
    "MANAKSTEEL": "MANAKSIA STEELS LTD",
    "MARUTI": "MARUTI SUZUKI INDIA LTD.",
    "MAXVOLT": "MAXVOLT ENERGY INDUS L",
    "NMDC": "NMDC LTD.",
    "UPL": "UPL LIMITED",
    "ANONDITA": "ANONDITA MEDICARE LIMITED",











    // "":"",











};

/**
 * Get the mapped symbol name for a given symbol
 * @param symbol - Symbol from My_Track.csv
 * @returns Mapped symbol name or the original symbol if no mapping exists
 */
export function getMappedSymbol(symbol: string): string {
    return STOCK_MAPPINGS[symbol] || symbol;
}

/**
 * Check if a symbol has a mapping
 * @param symbol - Symbol to check
 * @returns true if mapping exists, false otherwise
 */
export function hasMapping(symbol: string): boolean {
    return symbol in STOCK_MAPPINGS;
}


/**
 * Check if a symbol should be ignored
 * @param symbol - Symbol to check
 * @returns true if symbol is in the ignore list
 */
export function isIgnored(symbol: string): boolean {
    return IGNORED_SYMBOLS.includes(symbol);
}
